files:
  - source: /locale_example.ts
    translation: /%locale%/**/locale_example.ts
    dest: /src/admin/localization/locale_example.csv
    "first_line_contains_header" : true,
    "scheme" : "identifier,fi,source_phrase,de",
    type: csv
    "languages_mapping" : {
    "locale" : {
      "fi" : "src",
      "de" : "src",
      "sv-SE" : "src"
     }
    }
]
